### ISSUE TITLE
Shiny app : Silviculture

### ISSUE THREAD

**Issue by meztez** [bcgov/CCISS_ShinyApp#11]
- [x] Shiny render function
- [x] Style
- [x] Prepare silviculture dataset

**Comment by meztez** [comment]
@cmahony Could you me point in the direction of the information you want to appear in the silviculture tab. I could not find matching information in the CSVs nor in the database. I was not able to replicate the provided screenshot. Furthermore, I have located an Excel spreadsheet on the BC Gov website, but I would prefer not guessing.

**Comment by cmahony** [comment]
@meztez this is one that we will need help from @whmacken on. he has been on vacation but seems to be back at work this week. until then, it is fine to put this on the back burner.

**Comment by whmacken** [comment]
I pushed the stocking stand information tables to the data-raw/data_table/StockingStds folder.
I will need to send you a Forest Region spatial file to use. The stocking standards are by Region/BGC and knowing which Region the points are placed in is require to extract the correct stocking standard information.
StockStands is the main table. It links to the other two Stocking tables through the numeric ID in the Standard field
The Cross walk table links a mapped BGC with no Stocking information to a BGC that does.
I will also post a file with the footnote text.

**Comment by meztez** [comment]
@whmacken 
> I will need to send you a Forest Region spatial file to use.

Is it in the database?

**Comment by whmacken** [comment]
[ForestRegionBoundaries.zip](https://github.com/bcgov/CCISS_ShinyApp/files/6166989/ForestRegionBoundaries.zip)

**Comment by meztez** [comment]
@cmahony  I'm working on this tab now

**Comment by meztez** [comment]
@whmacken Were you expecting duplicated rows using Region, ZoneSubzone, SS_NoSpace, Species, Standard combination in stocking standards?

![image](https://user-images.githubusercontent.com/31039074/111849083-297ddc00-88e3-11eb-996f-34c8efdd8c74.png)

**Comment by whmacken** [comment]
I pushed an updated table where all the Region values should match the 6 regions in the shape file

**Comment by meztez** [comment]
I have similar duplicates in stocking height.
![image](https://user-images.githubusercontent.com/31039074/111849971-53380280-88e5-11eb-8537-bdb162c5bf7a.png)

For each stocking tables and crosswalk, do you expect a unique key? If not, what criteria do you want to base the merge on?

Thanks

**Comment by whmacken** [comment]
I will look at the duplicates. These are errors I need to fix. Will push shortly

**Comment by meztez** [comment]
I will use the first match for the time being, enjoy your weekend.

**Comment by whmacken** [comment]
Should be clean now.

**Comment by meztez** [comment]
You are a gem @whmacken. Thanks a lot.

**Comment by meztez** [comment]
I clean up the git history, you might want to use a git rebase before push changes to avoid polluting your commits with already commited code. Thanks
