### ISSUE TITLE
Running the app off of the DigitalOcean server

### ISSUE THREAD

**Issue by cmahony** [bcgov/CCISS_ShinyApp#16]
@psolymos is putting the CCISS postgres database onto DigitalOcean as part of a project to trial cloud computing processes for government data scientists. @meztez is creating a shiny app (this repo) that pulls from this database. @kdaust and @whmacken set up the database. it would be good to establish when and how to start running the app off of the digitalocean server. also, @meztez is creating vector tiles that likely would belong on digitalocean as well.  @psolymos any thoughts?

**Comment by psolymos** [comment]
Once the data is up we can give the access details to see how it works. As for vector tiles: how large files are we talking about?

**Comment by cmahony** [comment]
@meztez what is the total file size of the vector tiles?

**Comment by meztez** [comment]
```console
root@VaultingBlackberry:~# ls -alh /mapdata
total 26G
drwxrwxrwx  2 root root 4.0K Mar  8 07:07 .
drwxr-xr-x 22 root root 4.0K Mar  5 12:28 ..
-rw-r--r--  1 root root  14K Mar  8 07:18 becstyle.json
-rw-r--r--  1 root root  881 Mar  8 07:18 config.json
-rw-r--r--  1 root root  26G Mar  8 07:07 tiles.mbtiles
root@VaultingBlackberry:~#
```

**Comment by meztez** [comment]
Will have to loadtest it but it works fine on
![image](https://user-images.githubusercontent.com/31039074/110407237-84951080-8051-11eb-87fa-70517de81cdb.png)

**Comment by cmahony** [comment]
@meztez the app is on digitalocean and @psolymos is running some tests on it. should be available to you soon.
