### ISSUE TITLE
Species Feasibility Tab

### ISSUE THREAD

**Issue by whmacken** [bcgov/CCISS_ShinyApp#18]
Firstly a rename of the species suitability tab. We are using Feasibility for our modelling work which accounts for climate/site factors only. The term Suitability is used for the Chief Foresters ratings and are focused on ratings for timber production.
- [x] Add in all colours for legend feasibility ratings 
- [x] Bold tree species code part of Species label
- [x] Rename "predicted suitability" to "Predicted Feasibility"
- [x] Add in the 5th time period to Predicted Feasibility.  The ratings in the baseline tables (1961-1991) are "Historic", the 1991-2019 period is "Current" and then the three future time periods
- [x] Include all time period for all species for any species even where there is no feasibility occurrence 
- [x] Instead of 10, 25, 50 choices of species to report. Either "feasible only " or "all". The first category would include any species that is either in the Chief Foresters Suitability or is predicted feasible. The second choice would show species that have a some predicted feasibility in any time period. Ordered by feasibility rating first, species code second
- [x] The Chief Foresters Suitability rating should be taken from the Silviculture Tables. Use an "X" where a species is not listed

**Comment by meztez** [comment]
@whmacken Thanks a lot for the feedback

What do you mean all colours? How many colours do you expect.
![image](https://user-images.githubusercontent.com/31039074/111241942-88d2a800-85d4-11eb-9d74-b43a8ea124c0.png)

 > Include all time period for all species for any species even where there is no feasibility occurrence

Do you also mean all known BC species should appear in the table even if they are not in the site series? Or just the time period.

> Instead of 10, 25, 50 choices of species to report. Either "feasible only " or "all". The first category would include any species that is either in the Chief Foresters Suitability or is predicted feasible. The second choice would show species that have a some predicted feasibility in any time period. Ordered by feasibility rating first, species code second

Just to make sure, "all" would not include species that have no feasibility in all time period?

> The Chief Foresters Suitability rating should be taken from the Silviculture Tables. Use an "X" where a species is not listed
Great, I was wondering where that came from.

**Comment by whmacken** [comment]
I am only seeing this 
![image](https://user-images.githubusercontent.com/34073318/111338746-6a9c9480-8634-11eb-8f8e-f4229bfd9df1.png)
.

**Comment by whmacken** [comment]
For the "all" option. It would be species that show suitability in any time period. Only species where there is no suitability in any model or time period would be excluded.

**Comment by meztez** [comment]
I will make viewing test across browsers. Great input.

**Comment by meztez** [comment]
All items now in main
