### ISSUE TITLE
Shiny app : Export report

### ISSUE THREAD

**Issue by meztez** [bcgov/CCISS_ShinyApp#25]
Task breakdown

Export backend
 - [x] Export UI
 - [x] Site Series Filter
 - [x] Model Settings/Data Versions

Report Rmarkdown
 - [x] Output a map of submitted locations: an appropriately scaled bounded box of a BGC + Openstreetmap showing the user-selected location(s).
 - [x] Bar chart, feasibility report, and stocking standards table as specified in Task 2 above.
 - [x] Title block including BC government logo, date created, title, location details, etc.
 - [x] Caption for each graphical element
 - [x] Model/Report Information

**Comment by whmacken** [comment]
I've added a few more line items to your Export Task. 
Information like this should appear both on the report side bar in the app as well as in the output report.
![image](https://user-images.githubusercontent.com/34073318/112033072-47715980-8afa-11eb-8829-69842f61e0da.png)

**Comment by whmacken** [comment]
I've pushed an information table to the repo in the data-raw folder. Also attached here.
Also new Issue for About Tab
[CCISS_DataTable_Versions.zip](https://github.com/bcgov/CCISS_ShinyApp/files/6184333/CCISS_DataTable_Versions.zip)
