### ISSUE TITLE
About Tab: Add in 'Data Table Versions'

### ISSUE THREAD

**Issue by whmacken** [bcgov/CCISS_ShinyApp#28]
Add in sub menu page showing the data in the CCISS_DataTable_Versions .csv.
"Current versions of Information Tables, Maps, and Models used in this App"

**Comment by meztez** [comment]
@whmacken Would you mind rebasing your branch before committing new stuff? You can see it create conflicts when trying to push. Maybe you could do:

```git
git branch --track <new-branch> origin/main
```
Do your changes
```git
git push
```

And do a pull request.

I will the clean history for now, but it takes more time.

Thanks
