### ISSUE TITLE
Report Tab

### ISSUE THREAD

**Issue by whmacken** [bcgov/CCISS_ShinyApp#29]
Good start to this. Some ordering and reformatting is required. Some output options added.

- [x] Error: Feasible Only species should include species that are **either** suitable in the Reference Guide **or** predicted to the Feasible in the analysis. Right now I think they have to meet both criteria. If the species is not in the Ref guide but is projected as feasible then an 'X' should be placed in the Chief Forester suitability.  It is correct in the "Feasibility/Summary of Results" output but is incorrect in the Feasibility/Report  tab and  Report section as well as in the Climate Change column of the Silviculture tab/report.
- [x] Separate the export into two different dropdowns: Export Report and Export Data
- [x] Add in a data export to CSV format. Most of our users are not R capable.
- [x] Add in export report to PDF - format to be posted.

- [x] Reorder, renaming, standard label formatting some of the report sections.
- [x] Each section of report in all caps bold font
- [x] Labels for Site Series like 'Site Series: **SBSdw3/01** - SxwFd - Pinegrass'
Reorder/rename 7 report sections
1. Site Location (title of Map section )
2. Report Options (was called setup)
- [x] Date is in a weird format. Probably use year/month/day
3. CCISS Tree Feasibility (currently untitled)
- [x] Report Site: either the return hex tile number or like "SBSdw3 averaged" if averaged
- [x] Move Summary of Results section to Appendix
- [x] Move the feasibility Legend from below the BGC futures to here

4. Stocking Standards (rename from Silviculture) Add Rule line above to separate from Previous Section
- [x] Fix site series and Forest region label formats to be on a single line.
- [x] Flag Standards Species where rating is different from Climate Change. Blue if CCISS is Higher rating , Orange if Lower, Red and strike through if removed.

5. Predicted BGC Futures - Add Rule line above to separate from Previous Section
 
6.  Model Information
7. Data Point Georeferencing

**Comment by meztez** [comment]
> Error: Feasible Only species should include species that are either suitable in the Reference Guide or predicted to the Feasible in the analysis. Right now I think they have to meet both criteria. If the species is not in the Ref guide but is projected as feasible then an 'X' should be placed in the Chief Forester suitability. It is correct in the "Feasibility/Summary of Results" output but is incorrect in the Feasibility/Report tab and Report section as well as in the Climate Change column of the Silviculture tab/report.

Could you provide an example where the error occurs, the current filter between feasible only and all is based on the projected feasibility. https://github.com/bcgov/CCISS_ShinyApp/blob/13d164ff72cdfea1a2b7a299cb6106bf1a2a91f4/app/server/feasibility.R#L48.
1,2,3 are considered feasible. "All" means it is at least feasible in any period. So, to be clear, could you state your expectation for the following cases

| Chief Forester Suitability | Projected Feasibility | Mean Projected Feasibility | Feasible Only | All |
| --- | --- | --- | --- | --- |
| 2 | X | 4 | ? | ? |
| X | X | 3.5 | ? | ? | 

How would the following be treated for the stocking standards? Would the specie appears on both lines?
| Chief Forester Suitability | Projected Feasibility | Primary | Secondary | Tiertiary |
| --- | --- | --- | --- | --- |
| 1 | 3 | ? | ? | ? |
| 3 | 1 | ? | ? | ? | 

For the pdf, do you expect it to look like the html report? If yes, why not just print to pdf the html report. If not, how is it supposed to look?

> Reorder, renaming, standard label formatting some of the report sections.
Is it a separate item from the next items you mention? By itself it does not tell much.

The rest I understand it is one table per site serie and then each table goes to the appropriate section. Or you want all site series in the same table with the first column of the table being the site serie?

Thanks @whmacken, I will get on it.

**Comment by whmacken** [comment]
For the "Feasible Only" (and maybe the term is misleading). If the species has a rating in either the Chief forester or Projected Feasible - include it.  In your first table, row one would appear in both view options; the second line would only appear in All.

**Comment by whmacken** [comment]
I'm unclear on your stocking standards question. Are the twp rows both the same species?

**Comment by whmacken** [comment]
I will send a layout for the PDF on the morrow.

**Comment by meztez** [comment]
> I'm unclear on your stocking standards question. Are the twp rows both the same species?

Yes, the same specie, I,m wondering if you want the same specie to both appear in primary and tiertiary because CFRS says 1 but proj feasibility says 3.

**Comment by whmacken** [comment]
The species should be in the primary row for CFR and then in the tertiary row for the Climate Change column. This is an example where the model is suggesting that our current CFR guidance is too liberal and the species should probably be planted less than it is currently

**Comment by meztez** [comment]
I'm dump, sorry, this is what it is already doing... I guess I was confused when you stated there was an error.

**Comment by whmacken** [comment]
![image](https://user-images.githubusercontent.com/34073318/112499835-15a00300-8d45-11eb-8346-4864791b85fc.png)
In this example reprot the Summary of Results is showing all the species that are either in the CFR or are projected to be suitable.
But the Feasible Species section only shows two species.

**Comment by whmacken** [comment]
![image](https://user-images.githubusercontent.com/34073318/112500260-762f4000-8d45-11eb-9c21-df67a99c6ad4.png)
Similar issue in the Stocking Standards all the correct CRF species are listed but not the projected Feasible species in the Climate Change column

**Comment by whmacken** [comment]
I'm using FireFox again. That might be the issue. I just ran a report in Chrome and it looked correct....

**Comment by meztez** [comment]
That's weird. I'll look into it.

**Comment by meztez** [comment]
> ![image](https://user-images.githubusercontent.com/34073318/112499835-15a00300-8d45-11eb-8346-4864791b85fc.png)
> In this example reprot the Summary of Results is showing all the species that are either in the CFR or are projected to be suitable.
> But the Feasible Species section only shows two species.

Yeah that was on purpose, will switch the filter

**Comment by meztez** [comment]
> I'm using FireFox again. That might be the issue. I just ran a report in Chrome and it looked correct....

It was not Firefox, it was to a filter that only processed Species from Climate Change that were in the standard.

**Comment by meztez** [comment]
I was able to shave off another 500ms from the "generate results" process. Yay

**Comment by meztez** [comment]
test locations html report attached per requested spec

[test_locations.zip](https://github.com/bcgov/CCISS_ShinyApp/files/6226166/test_locations.zip)
