### ISSUE TITLE
PDF Report

### ISSUE THREAD

**Issue by whmacken** [bcgov/CCISS_ShinyApp#30]
Our ultimate goal with the reports is to have a formatted report that a forester would submit with a reforestation plan.
So the PDF report would be more structured than the HTML report.
For this any site information should be put on the first page normal letter size PDF (8.5x11)
Then all information for a single site series put on the next page, with every site series getting its own page.
If there is more than one site to be run in the report then all the this is then repeated.

**Comment by whmacken** [comment]
![PDF report site info page 1 layout](https://user-images.githubusercontent.com/34073318/112502601-72042200-8d47-11eb-9ded-2e91d5d21d66.jpg)
![PDF report site series pages layout](https://user-images.githubusercontent.com/34073318/112502626-74667c00-8d47-11eb-995d-cb06234200aa.jpg)

**Comment by whmacken** [comment]
Excuse the chick scratch writing. A sketch of the PDF report layout.

**Comment by meztez** [comment]
sample PDF report attached per requested spec, also available on live deployment

[test_locations.pdf](https://github.com/bcgov/CCISS_ShinyApp/files/6226170/test_locations.pdf)

**Comment by cmahony** [comment]
@meztez this looks excellent. There one modification required. 
1. the reports are only showing the "feasible only" species. the reports should default to showing "all species". there should be a UI toggle to allow the user to control whether to show "feasible only" or "all", like in the Feasibility tab.

**Comment by meztez** [comment]
Done
