### ISSUE TITLE
migrate to shinyapps.io BCGOV account

### ISSUE THREAD

**Issue by meztez** [bcgov/CCISS_ShinyApp#31]
The app has been migrated to a temporary shinyapps.io account

at https://neoxone.shinyapps.io/BCGOV_CCISS/

It should give you an idea of what it will look like when you deploy there.

**Comment by whmacken** [comment]
The PDF report function does not seem to be functioning. Colin said it successfully ran for him last week but not now.

**Comment by meztez** [comment]
Confirmed

```
Warning: Error in is_remote_protocol_ok: Cannot find headless Chrome after 20 attempts
```

**Comment by meztez** [comment]
Seems to be an issue with shinyapps.io as the code as is works fine outside it.

I have redeployed on a new droplet in the project DO while the shinyapps.io community investigate the issue.

http://178.128.230.70/shiny/cciss
