### ISSUE TITLE
install of bccciss package failing

### ISSUE THREAD

**Issue by whmacken** [bcgov/CCISS_ShinyApp#33]
Installing package into ‘C:/Users/whmacken/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'bccciss' ...
** using staged installation
** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.3/include" -DNDEBUG  -I'C:/Users/whmacken/Documents/R/win-library/4.0/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.3/include" -DNDEBUG  -I'C:/Users/whmacken/Documents/R/win-library/4.0/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c bccciss.cpp -o bccciss.o
C:/rtools40/mingw32/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o bccciss.dll tmp.def RcppExports.o bccciss.o -LC:/PROGRA~1/R/R-40~1.3/bin/i386 -lR
installing to C:/Users/whmacken/Documents/R/win-library/4.0/00LOCK-bccciss/00new/bccciss/libs/i386

*** arch - x64
"C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.3/include" -DNDEBUG  -I'C:/Users/whmacken/Documents/R/win-library/4.0/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.3/include" -DNDEBUG  -I'C:/Users/whmacken/Documents/R/win-library/4.0/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c bccciss.cpp -o bccciss.o
C:/rtools40/mingw64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o bccciss.dll tmp.def RcppExports.o bccciss.o -LC:/PROGRA~1/R/R-40~1.3/bin/x64 -lR
installing to C:/Users/whmacken/Documents/R/win-library/4.0/00LOCK-bccciss/00new/bccciss/libs/x64
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'data.table' was built under R version 4.0.5
Execution halted
ERROR: lazy loading failed for package 'bccciss'
* removing 'C:/Users/whmacken/Documents/R/win-library/4.0/bccciss'
Error: Failed to install 'bccciss' from GitHub:
  (converted from warning) installation of package ‘C:/Users/whmacken/AppData/Local/Temp/Rtmp4MLG3W/file5e3066413751/bccciss_1.0.0.9990.tar.gz’ had non-zero exit status

**Comment by meztez** [comment]
Your R install is not up tp date with CRAN compiled packages for windows.

You can either:
- Install R 4.0.5 to match windows binaries version
- Change your options to prevent warning from converting to error `options(warn = 0)` <- my suggestion
- Install `data.table` from 4.0.4 binaries (and possibly all other dependencies)

**Comment by whmacken** [comment]
Thank Bruno. An all package update seems to have resolved the loading of bccciss though the error message around data.table is still displayed.
> pool <- dbPool(
+   drv = RPostgres::Postgres(),
+   dbname = Sys.getenv("BCGOV_DB"),
+   host = Sys.getenv("BCGOV_HOST"),
+   port = 5432, 
+   user = Sys.getenv("BCGOV_USR"),
+   password = Sys.getenv("BCGOV_PWD")
+ )
Error: fe_sendauth: no password supplied
Now, I'm not sure where or what should be entered here.

**Comment by meztez** [comment]
Check your email or spam for something from @boostao.ca. If you do not get it in the next 5 minutes. I'll try another alternative.

**Comment by whmacken** [comment]
Updated R and removed error messages. Pasted DO info into .Renviron and my local version now runs cleanly.
Thanks very much
