### ISSUE TITLE
Updating bccciss package when data tables are updated

### ISSUE THREAD

**Issue by whmacken** [bcgov/CCISS_ShinyApp#34]
User ignorance to be corrected. I am updating a raw data table (feasibility) and then running the create_package_data.R script to update to the package .rda format successfully. This new data is not used when I then rerun the index.rmd as a local instance.
Not sure what I'm needing to do to implement the changes- am I needing to regenerate the bccciss package? If so I'm not sure if I actually know the procedure for this.

**Comment by meztez** [comment]
Yes the package has to be updated. You can do this from RStudio.

Or commit your new rda files and reinstall from github.

![image](https://user-images.githubusercontent.com/31039074/116282664-07387300-a759-11eb-8428-2a8e56c429d6.png)

**Comment by whmacken** [comment]
Thanks. Rebuild works fine though I have to manually remove the package from my library to allow it to be rebuild

**Comment by meztez** [comment]
Just a simple R restart on windows. (ctrl + shift + F10 in RStudio)

The package has compiled code. When the library is loaded on windows, the library C code is locked by the R process and can not be replaced.
