### ISSUE TITLE
Shiny layout script - where is it?

### ISSUE THREAD

**Issue by whmacken** [bcgov/CCISS_ShinyApp#35]
Another user error problem. I'm used to a long scripts for Shiny where everything is run from one big app.r, which is probably a terrible way to do it. But in the CCISS app the index.rmd is simply working the user UI and does not have the web layout - so where are the layout parameters for the app? I was going to change some of the tab labels etc but its not clear which script that resides in.

**Comment by meztez** [comment]
index.rmd? The layout is generated from flexdashboard. Do you have a specific label in mind?

**Comment by meztez** [comment]
An example tabset:
https://github.com/bcgov/CCISS_ShinyApp/blob/b03401351b0f26152847e483dfba7946cea2f575/app/index.Rmd#L127

https://rmarkdown.rstudio.com/flexdashboard/layouts.html#tabset_column

**Comment by whmacken** [comment]
I think I see it now. The flexdashboard knows how to read/intpret the header from the format in the index.rmd.
I'll read up on that tool.

FEASIBILITY
=====================================  

Inputs {.sidebar data-width=230}
-------------------------------------

###### Filters
