### ISSUE TITLE
Internal BCGov network does not connect to tileserver

### ISSUE THREAD

**Issue by kdaust** [bcgov/CCISS_ShinyApp#41]
@meztez wondering if you have any suggestions - when I open the app connected to bcgov network, everything works fine, and the reports all generate, but the BGC map doesn't show up (all you see is the base mapbox map). My guess is that some security measure in the government network is blocking the app from connecting to the tileserver. Do you have any ideas for getting around this (I'm fairly ignorant about firewalls/network security etc so wasn't really sure where to start). And since I'm also going to be using a tileserver for the feasibility app I'm working on it would be nice if people within Gov were able to use it.
Many thanks!

**Comment by meztez** [comment]
You can host the tileserver on a domain with a valid https certificate or buy a domain and use a valid certificate. It is probably blocked by your internet firewall. You can inspect the the tileserver request with the browser developer tools (Network) to validate the type of error you are getting.

Using my work internet, it will not even let me open a websocket connection to the app.

**Comment by meztez** [comment]
In my org, we have a service desk that can issue ssl certificate with a domain so you can make your app compliant the your network security. Unfortunately, I know next to nothing about BC Gov internal network.

**Comment by kdaust** [comment]
Ok I think that makes sense. Thanks!
