### ISSUE TITLE
Login info for shiny-server droplet

### ISSUE THREAD

**Issue by kdaust** [bcgov/CCISS_ShinyApp#42]
@meztez sorry for the questions - I'm trying to access the shiny-server droplet (i.e. 178.128.230.70) to change the database to a new droplet, and I'm unable to log in via ssh (it works fine for the other droplets in that team). I'm guessing it's because you created the droplet before I had ssh keys uploaded. Do you have the login info for it so I can access that way, or could you add my ssh key?
Thank you!

**Comment by meztez** [comment]
There is an authorized key on the droplet with your credentials.
ssh-rsa AAAAB3NzaC1y......wcFdeA7sG+/J4o3 kirid@MSI

Send me another key to info@boostao.ca if this is not the one you want.

**Comment by kdaust** [comment]
Oh excellent, sorry I forgot I'd set that one up. Thanks!

**Comment by meztez** [comment]
Maybe you already know.

The postgres service on the new server is unable to start.

```r
root@postgres-cciss:~# systemctl status  postgresql@12-main
● postgresql@12-main.service - PostgreSQL Cluster 12-main
   Loaded: loaded (/lib/systemd/system/postgresql@.service; indirect; vendor preset: enabled)
   Active: failed (Result: protocol) since Mon 2021-05-17 02:27:14 UTC; 3min 54s ago
  Process: 1039 ExecStart=/usr/bin/pg_ctlcluster --skip-systemctl-redirect 12-main start (code=exited, status=1/FAILURE)

May 17 02:27:14 postgres-cciss systemd[1]: Starting PostgreSQL Cluster 12-main...
May 17 02:27:14 postgres-cciss postgresql@12-main[1039]: Error: /mnt/postgres/postgresql/12/main is not accessible or does not exist
May 17 02:27:14 postgres-cciss systemd[1]: postgresql@12-main.service: Can't open PID file /run/postgresql/12-main.pid (yet?) after start: No such f
May 17 02:27:14 postgres-cciss systemd[1]: postgresql@12-main.service: Failed with result 'protocol'.
May 17 02:27:14 postgres-cciss systemd[1]: Failed to start PostgreSQL Cluster 12-main.

```

Let me know if I'm overreaching. I quite like seeing the app working.

**Comment by kdaust** [comment]
Yes that's absolutely my fault; I had some issues moving the database mostly because I'm not super familiar with digital ocean especially the volumes. Working on fixing it now. Thanks so much for the note though, and absolutely not overreaching.

**Comment by kdaust** [comment]
Back up and working well :)
