### ISSUE TITLE
Best way to push changes to shiny server

### ISSUE THREAD

**Issue by kdaust** [bcgov/CCISS_ShinyApp#43]
Hi @meztez - just a quick question: what would you recommend as the best way to update the app on the shiny-server droplet? Is it best to say rsync or cp files over, or should I set it up with git? Many thanks!

**Comment by meztez** [comment]
When developping, I used that :
https://github.com/bcgov/CCISS_ShinyApp/blob/d538679522bc111eeafb181dc43d907a2f3e1f8e/data-raw/scripts/bigshinygisstudio.R#L108

For digitalocean, it could be turned into a function like we do for the plumberDeploy package.

You could also use github actions linked to this repo and use repo secrets to set up SSH keys.

The reason I'm not too eager on rsync is that you probably want somekind of automated testing before deploying? Maybe you could use a staging step (using the same app at a different url on the same server).

Shinyapps.io, you can just use RStudio Connect button.

**Comment by kdaust** [comment]
Thank you, that's very helpful!
