### ISSUE TITLE
Multiple layers on tileserver

### ISSUE THREAD

**Issue by kdaust** [bcgov/CCISS_ShinyApp#50]
Hi @meztez - hope you're well! I'm wanting to add a new layer to the tileserver - basically linework for district boundaries. Do you know what the proper way to do that is? As far as I can tell, the easiest option is to upload all the layers at once, and then when it creates the tiles.mbtiles, that will have both layers and I can adjust the javascript function to select one or the other. However, since the BGC layer takes a while to tile, and it's already there, it would be nice to just add another layer. If I upload another shp file and save the tile output as a different name (i.e. so I then have two .mbtiles files), do you think that would work? I realise that I would then need to change to config.json file to serve both.

I'd appreciate any advice you have! Thanks :)

**Comment by kdaust** [comment]
What I've ended up doing is just editing the config file to create separate data sources for each .mbtiles file, and then I can specify the layer by adjusting the server URL in shiny. Seems to work ok, but if you have a better way of doing it I'd love to know!

**Comment by meztez** [comment]
That's how I would do it. Separate mbtiles for each source since zoom level availability and other parameter can be different per tile layer.

**Comment by kdaust** [comment]
Awesome, thanks so much!
