### ISSUE TITLE
Plotly vs ggplot?

### ISSUE THREAD

**Issue by kdaust** [bcgov/CCISS_ShinyApp#52]
Hi @meztez! Hope you're well. I'm currently adding some new functionality (including some new plots) to the app, and was wondering about the benefits of using an interactive javascript library like ploty (as you did for the BGC futures plot) vs a static renderPlot output (my plots are currently ggplot2). Assuming they don't need to have any interactivity, is there any benefit to converting them to plotly? Thanks!

**Comment by cmahony** [comment]
@kdaust here is my unsolicited input: I'm generally moving over to plotly as i do think the interactive functionality adds quite a bit to the user experience. see the "choose models" tab in my [cmip6-bc](https://bcgov-env.shinyapps.io/cmip6-BC/) app. Much better than the static version in my [ccsummary ](https://bcgov-env.shinyapps.io/ccsummary-Kamloops/) apps.

**Comment by kdaust** [comment]
Thanks @cmahony! I agree with you - certainly works great in the choose models plot! I haven't used plotly much before - I'll have to get into it!

**Comment by meztez** [comment]
With plotly I don't have to think about recomputing the plot when the user change the browser window dimension. It is an esthetics choice.

**Comment by kdaust** [comment]
Thanks! Appreciate the feedback :)
