### ISSUE TITLE
CCISS_Spatial_exports.R

### ISSUE THREAD

**Issue by cmahony** [bcgov/CCISS_ShinyApp#65]
The CCISS_Spatial_exports.R script is designed to provide input data to the ccsummary apps. there are a few issues that need to be resolved: 

- [x] need BGC predictions for the 1961-1990 reference period. this is the correct baseline for comparison to predictions for other periods (i.e., modeled vs. modeled for an apples-to-apples comparison). (kiri)
- [x] need BGC projections for the 2001-2020 observed normals (kiri)
- [x] dbGetBGCPred() currently pulls only `period = c(,'2021','2041','2061','2081')`. we need 2001-2020. i was able to change this in data_etl.R but was getting an error when trying to rebuild the ccissdev package. (kiri to show colin how to implement this)
- [x] remove sspreds component of the bgc_ss_spatial (colin or kiri)
- [x] a simple version of the edatopic overlap function to return projected suitability for a specified model/scenario/period/edatope/species. i.e.: provide the reference and projected BGCs and get the change in suitability for a specified edatope and species. (kiri)
- [x] for the bgc_ss_spatial() function, need to mask centroids outside of the study area boundary using 
`bnd_cnt <- st_intersection(bnd_cnt, st_as_sf(bnd)) ` (colin)
- [x] create a separate function to create a dem and climr input table for the study area, and remove this from the bgc_ss_spatial() function. (colin)
- [x] use climr to calculate the climate import tables (colin)
- [x] code for exporting the species rasters (colin)
- [x] code for exporting the species summary tables. (colin)

**Comment by kdaust** [comment]
Couple comments for further discussion:

- The CCISS database doesn't actually have projections for the 1961-90 period. We'll need to add those, but that might be best to wait until we do the next version using climr.
- The database has predictions for 1991-2020, but not 2001-2020. Something else to change in the next version.
- I can certainly made a function to provide feasibility changes for a given GCM/scenario. But might we not also want to keep the full edatopic overlap version, as that's what's being using in the CCISS tool?

**Comment by cmahony** [comment]
closing as these tasks were done. opening a new issue for generalizing the cciss spatial app.
