### ISSUE TITLE
spatial module

### ISSUE THREAD

**Issue by cmahony** [bcgov/CCISS_ShinyApp#66]
@kdaust I've completed the updates to the spatial module. I've run it for the Nimpkish and sunshine coast study areas i tried running it for BC, but i got a climr error saying there wasn't enough data... something for you to try yourself. 

a few notes about the way i've structured things. 

- the app is in a spatial_app directory in the CCISS_ShinyApp repo. 
- the files for the different study areas go into difference subdirectories of the "data" directory for the app
- the files are all separate tiny files for quick reading into the app. i'm assuming you have a better way of doing this. 
- I've been targeting grid resolutions that produce ~50-80K grid cells in the study area. more would have taken a long time to generate the data, but perhaps would look better and i think the app can handle it (~150k cells?). something to consider
- for now, i'm only doing spp245. i've set things up to accomodate user-selected scenarios if we want to add that, but for now it doesn't seem worth the data storage. 

This is now at a point where it needs your skill set. here are some next steps: 

- [ ] the goal is to have a cciss tool module or a separate app that allows users to select their studyarea and then see the results for that area. as discussed these could be the 12 FLP areas or it could be all TSAs/TFLs in the province. the data are about 30-50Mb per study area. 
- [ ] refactor app from raster to terra. I tried, but i couldn't get the BGC colour schemes to work due to what seemed to be a bug in how terra interacted with leaflet. 
- [ ] move the data onto digital ocean. 
- [ ] update the change map to the new colour scheme (this will require changing how the change factors are calculated in the cciss_spatial_exports.R script). 
- [ ] update the loss/gain map to indicate where there is a significant bifurcation of trends among the ensemble (also requires modifying cciss_spatial_exports.R)
- [ ] experiment with higher resolutions (~150k cells within study area boundary?)

**Comment by kdaust** [comment]
Moved to spatcciss repo
