### ISSUE TITLE
Shiny app : Map tab

### ISSUE THREAD

**Issue by meztez** [bcgov/CCISS_ShinyApp#8]
The main interaction with the tool

Leaflet
- [x] Base layers (Satellite, Hillshade, OpenStreetMap)
- [x] Zones and Subzones Variants custom layers
- [x] Crop water from geometries
- [x] OSM Geocoder, Control, Measurement
- Added interactions
  - onClick
    - [x] Add points to selected points table
    - [x] Show feature information + BCG in a popop
    - [x] + elevation 
    - [x] Add marker to map
  - onHover
    - [x] Show BCG information

Points management
- [x] Single point input
- [x] Input file point input with semi-smart detection of coordinate (csv, txt, xslx?) plus validation
- [x] RCP toggles
- [x] Report level options (individual vs average)
- Points table
  - [x] Editable simplified points information
  - [x] Remove point
  - [x] Scrollable past a number of points

**Comment by whmacken** [comment]
This works great. Two things might help in the map.
Add city dots and main highways to the 'always on top' map base information. Enough to allow users to largely place themselves in the province when zooming around.
I like the hover emphasis for the subzone/variant. But the user will want to see the base layers underneath when selecting sites in many cases. So the emphasis should either be the outline only, or be related to the transparency setting for the main BGC layer.

**Comment by meztez** [comment]
@whmacken 

There are three labels layer available as I was not sure which one you would prefer, I will set the default to Mapbox labels which has road information + park.

There is a mini-map in the bottom right corner and geolocation finder when you click the magnifying glass top left corner.

Instead of increasing opacity on mouseover, I will decrease it.

**Comment by cmahony** [comment]
@meztez i like the approach you have taken of full transparency on mouseover. 

the geolocation finder is great but it puts a blue circle on the searched location that i can't get to go away. could you remove the blue circle?

**Comment by meztez** [comment]
Blue circle now goes away on search tool collapse. Unless, you have something else, I would be done with the map tab.

**Comment by cmahony** [comment]
@meztez the map tab looks great to me. thanks!
@whmacken can you close this issue if you don't have further change requests to the map tab? i'm thinking we can do tweaks  (like the legend) ourselves at a later date.

**Comment by whmacken** [comment]
@meztez Yes the map interface is excellent.
2 issues with the other ways of adding points 
1. We need an expanded error capture in the upload a CSV. I mistakenly tried to add a file where all locations were  positive longitude so none of the points fell within BC.  This causes the app bomb and asks for a reload. I then used a file with points both inside and outside BC and your code successfully manages and reports this to user.
2. I cannot figure out how to use the Add button. Values can be added to the added row but I'm not sure how to then submit and actually add them.

**Comment by whmacken** [comment]
@meztez @cmahony The Generate button. The results of the analysis are done on the fly so we don't really need this. But I think we thought that users might look to a button to assure themselves something has happened. 
If this is the purpose then maybe a bigger coloured button below all the location/model information labelled  "Refresh Results" might be the ticket.
![image](https://user-images.githubusercontent.com/34073318/111662461-2bee1200-87cd-11eb-8ceb-36899cd6d060.png)

**Comment by meztez** [comment]
On the fly results are relatively costly as they trigger each time a point change. At the moment it takes about 1 seconds to redo the analysis. See comment here on why I decided to use a generate button.
https://github.com/bcgov/CCISS_ShinyApp/blob/d9f44e54fd7354caf63a630f3a28bb641c4a3975/app/server/generate.R#L2

I'll check out the reload-bomb and see if can do something about the edit points things without having to rewrite the datatables js library.

**Comment by whmacken** [comment]
OK. I think it probably feels more 'normal' for users to hit a button to report once they are finished with points.
I do think making it more prominent and central at the bottom of the report options is probably a good idea. But we're getting into the details at this point - I think this map interface is working very well for our purposes.

**Comment by meztez** [comment]
Add points is now a modal window
Better upload file validation and messaging
Bomb was due to elevation raster having overlapping extent, using an aggregation function (max) to return a single elevation per point
Big blue generate/refresh button

**Comment by meztez** [comment]
New issue should be filed separately
